version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345asd
      POSTGRES_USER: postgres
      POSTGRES_DB: BotUsers
    ports:
      - "5433:5432"
  app:
    build: .
    environment:
      DB_URL: postgresql://postgres:12345asd@db:5432/BotUsers
    depends_on:
      - db
